### ISSUE TITLE
Check operational constraints for subtitle XML files

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#135]
ST429-2:2009:

_**8.4.4 Maximum Rate of Occurrence for On-Screen Timed Text**
Up to three (3) subtitle instances may be visible on screen at any time. The visibility period of an instance shall include fade-in and fade-out times. A subtitle instance shall contain no more than six (6) Text elements or three (3) Image elements._

ST429-2:2013:

_**8.4.4 Maximum Rate of Occurrence for On-Screen Timed Text**
Up to two (2) subtitle instances may be visible on screen at any time. The visibility period of an instance shall include fade-in and fade-out times. A subtitle instance shall contain no more than six (6) Text elements or three (3) Image elements._

Does clairmeta currently check the above constraints?

**Comment by remia** [comment]
My guess is that we don't check those constraints. 

I'm still unclear if we should support all the history of SMPTE standard revisions because of the added complexity. It is probably needed for archiving purpose, but we need to think about a good way of implementing this to avoid adding conditions everywhere in the code (that is already quite in a bad state for subtitle!).

The first check about the maximum subtitles visible at any time should probably be added in the python code.

The second would probably be best implemented by updating the corresponding XSD schema, but I'm not sure if we should start making our own modifications of those SMPTE authored schema, what do you think @matmat ? This is relate to #134 that could also be solved by updating the SMPTE XSD.

**Comment by matmat** [comment]
I thinkt that a good start would be to check if the tested content does not validate against the latest revision of the standard as this is mostly the most strict.

My feeling is that the stricter constraints in the later revisions in the standard is motivated by hardware and/or software limitations of already fielded equipment.

**Comment by remia** [comment]
Started working on it in #169, it would be nice to have test material to validate this one.

**Comment by remia** [comment]
These will be merged in #207
