### ISSUE TITLE
Please document how to bypass checks on the cli

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#208]
I can't get e.g. the hash checks bypassed when running clairmeta on the cli. How do you it with the new bypass_list?

**Comment by jamiegau** [comment]
From my understanding, you need to supply a profile.json file.

On the main README.md page, you will see a topic of
"Custom profile check"

This use to reference items you can also skip, but it has been removed from the example some reason???
I use Python code to control profile application, but build the profile.json in code and pass that (All in python).
But it should all work based on that profile you write.

Maybe remi can expand on the topic and whats going on.

**Comment by remia** [comment]
The idea was that now that you can have checks run once and compared against multiple profiles, the idea of a bypass list linked to a particular profile didn't hold anymore. What if the default profile bypassed the hash checks then your second profile not? I don't think we want the complexity of supporting partial checks run to cover the difference between the two profiles in terms of bypassed checks.

I agree this cause issues for the CLI path and thanks for raising that point. One pragmatic approach would just be to keep the bypass list inside the profile.json file and simply warn the user if there is a conflict like mentioned above. Open to any suggestion here.

**Comment by jamiegau** [comment]
Yes, interesting issues.
Just to go over the implementation in my mind.
When using clairmeta under this new model.  It would produce a first-pass QC output file (json blob?) that has everything it discovered, then second pass, the profile is applied resulting in the typical output of ERRORS and WARNINGS we currently see.

In regular use as of today, this 1-pass-json-blob file would be temporary and deleted after use.  But with command line arguments, You could specifically specify an output path to save it to or specifically only do this pass with command line arguments.  Then apply the profile(s) against the json-blob as desired, producing results for different profiles.

python wise, you could manipulate this anyway you like, for example keeping the json-blog in a database and apply profiles as required.

But yes, if this is the new feature set, how does turning off key processes on creation of the json-blob apply to this...
When using a json-blog that has certain data-points missing  when checked against a profile just flag that check that has incompletely data as underminable, Master QC-pass missing required data?

This may be a required capability as..

What happens if more QC checks are added at a later date and then this is applied to older json-blobs that may not contain the required data?

**Comment by remia** [comment]
I think we need to think pragmatically here, given the limited resources on the project, I would probably say we don't add any new feature to the command line, we just need to maintain what was available, ie. a way to bypass specifics checks. This is still possible with the bypass key of the profile.json file although it generates a warning currently, adding a dedicated hash bypass flag is also a possibility.

I'm not in favour of supporting an intermediate format to store the intermediate checks results at this point because it would be a lot of trouble for a probably limited use case. We would have to version the format, handle version conflict, new version adding new checks as mentioned, as well as removed checks, etc. It's also not clear to me if you want to base your quality check on data gathered potentially several months beforehand.

**Comment by jamiegau** [comment]
I must admit, this idea has become far more complex very quickly.  A bit of a pandora's box.

> I'm not in favour of supporting a format to store the intermediate checks

I am confused by this statement.  As if we can apply several PROFILE checks on a QC-pass, then by definition, your storing a intermediate pass to apply the numerous profiles against.
Dropping this to a file or into a DB would be a common sense use model.

The more I consider this the bigger job it looks like.  it really depends on the  implementation.

I'll try to have a look at the repo with the implementation when I can.

**Comment by remia** [comment]
> I am confused by this statement. As if we can apply several PROFILE checks on a QC-pass, then by definition, your storing an intermediate pass to apply the numerous profiles against.
> Dropping this to a file or into a DB would be a common sense use model.

The way I see it, it's only a temporary representation is not meant for longer term storage, that's why I'm now reconsidering this 2 different function call approach.

**Comment by remia** [comment]
I'm going to revert all the changes proposed for the time being so that we can push a new release.
