### ISSUE TITLE
Windows dependencies installation

### ISSUE THREAD

**Issue by kieranjol** [Ymagis/ClairMeta#45]
Hi,
Are there any instructions for adding the dependencies on Windows? I'm thinking of asdcp and libmaic in particular. You can use homebrew or apt-get on non windows machines, but on  Windows (we do not have access to Windows Subsystem for Linux), this becomes a bit more awkward.

**Comment by remia** [comment]
Hi Kieran,

The main issue is asdcplib because where are trying to remove libmagic usage from the library (already no longuer used for DCP).

I tried to compile asdcplib on Windows and it worked (with some modifications to the makefile for 64bits build), we could try to build and package it from the CI environment. Travis that seems to support [windows build](https://docs.travis-ci.com/user/reference/windows/) and [Chocolatey](https://chocolatey.org/) package manager. There might also be a way to package it in [python wheel](https://packaging.python.org/guides/packaging-binary-extensions/) but it's primarily for C extensions like the ones numpy use I think, not sure if this could apply for executables...

We are not currently using Clairmeta on windows here so we may not be able to dedicate much time on this at the moment.

**Comment by remia** [comment]
By the way, I'm not currently aware of any Brew formula for asdcplib on mac OS, could be good to add.

**Comment by kieranjol** [comment]
The homebrew forumla is a few years old but it is linking to what appears to be an up to date mirror of the asdcp source code for compilation: https://github.com/cbenhagen/homebrew-video/blob/master/asdcplib.rb

it would be great if there was some sort of way to package asdcp in the pip installation alright (if that's what you meant..)

**Comment by remia** [comment]
Thanks for the link, indeed I forgot that repository ! It's not the official asdcplib distribution though.

Yes that's what I proposed but I think the right way is to have an installation based on independant package like what we have currently for debian, that way we can manage component version independantly.

**Comment by kieranjol** [comment]
I ended up getting asdcp working OK on windows - the problem I have is now libmagic. I'm struggling to get that working on windows as the easiest instructions i've found have been for WSOL in Win 10, but I am currently using win 7.

**Comment by kieranjol** [comment]
Ok so the rough steps for windows compilation are:
* pip install clairmeta
* pip install python-magic-bin==0.4.14
* install  [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145 ) as libmagic needs vcruntime140.dll
* get asdcp-lib from http://carlh.net/asdcplib and place those exe files somewhere that python can find them

**Comment by remia** [comment]
Just to mention that libmagic dependency will be removed in the next version (should be gone in develop branch already). That could ease the process a bit.

**Comment by remia** [comment]
Closing this, an example can be found in the new Github Action workflow file for Windows.
