### ISSUE TITLE
Windows 7  - could not initialise log file

### ISSUE THREAD

**Issue by kieranjol** [Ymagis/ClairMeta#52]
Hi,

On windows 7, I get an error when clairmeta is imported:
`2018-11-19 12:32:56,288 - Clairmeta - ERROR - Could not intialize log file : [Error 3] The system cannot find the path specified: 'C:\\Users\\PCCC/Library/Logs'`
This isn't a fatal error, clairmeta continues to work, but it probably should be changed.

My guess is that it originates from this line: https://github.com/Ymagis/ClairMeta/blob/243200e264f7e88007b0ad35dd854b3a7fe7daef/clairmeta/settings.py#L8 
and this folder does not exist by Default in unix systems. So I guess clairmeta could:
* create ~/Library
* ask the user to create ~/Library
* check if not unix and if not, use some other default logging location on Windows

**Comment by remia** [comment]
Indeed the current default log location is not cross platform, I'll look at what is available with python to discover appropriate log folder depending on the os used.

Then we will probably use this as default and only provide a config settings to override this for the user (taking responsability for specifying a valid path, otherwise we would use the default emplacement as a fallback..).

**Comment by remia** [comment]
Don't find anything to pick a standard location automatically, I guess the most obvious thing would be to leave this field empty by default (ie. no log file is written) and let the user (or deployment tool) to specify it based on the context.

**Comment by remia** [comment]
See #69
