### ISSUE TITLE
Believed incorrect namespace error with SMPTE subtitles

### ISSUE THREAD

**Issue by cth103** [Ymagis/ClairMeta#72]
I have a SMPTE DCP with subtitles:

http://dcpomatic.com/Clairmeta_FTR-1_F_MOS_2K_20190106_SMPTE_OV.zip

ClairMeta says "Namespace unknown : dcst"

The XML (inside the subtitle MXF) starts 

<dcst:SubtitleReel xmlns:dcst="http://www.smpte-ra.org/schemas/428-7/2010/DCST" xmlns:xs="http://www.w3.org/2001/XMLSchema">

I think ClairMeta is incorrectly looking for "dcst" as one of its accepted namespaces (in settings.py) instead of looking for http://www.smpte-ra.org/schemas/428-7/2010/DCST

If I'm right about this, I don't know how you fix it as AFAICS asdcp-info only returns the namespace name, not its value.  check_subtitle_cpl_xml() gets 'NamespaceName' from the probe.

Let me know if I can provide any more information.

Thanks!

**Comment by remia** [comment]
Hi Carl,

Thanks for the report, I took a look at the problem and here is what I think at the moment.

Accoding to SMPTE 429-5, the TimedTextDescriptor's NamespaceURI value shall give the namespace value and not the prefix, here is an extract from the document.

![capture d ecran 2019-01-08 a 08 48 46](https://user-images.githubusercontent.com/1922806/50817082-00d12380-1323-11e9-894d-0b6258b130a1.png)

Clairmeta rely on the NamespaceName value that is (most likely) an alias for the NamespaceURI value (from asdcplib source code : `TDesc.NamespaceName = TDescObj->NamespaceURI;`). When this is not the namespace value, Clairmeta can't find an appropriate XSD schema for checking the XML and give this error.

Agree that this may not be the most clear error as this is caused by an invalid MXF header tag and not an XML issue.

Let me know if that makes sense.

**Comment by cth103** [comment]
You are right!  Thank you for investigating, and sorry for getting the wrong idea.  i have fixed my code and the ClairMeta checks now pass.
